// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm8avWwk4TL8ehqVJyM51HJex1jE4-ajk',
    appId: '1:748579942028:web:a5cdeea33e5bfd5b4955a9',
    messagingSenderId: '748579942028',
    projectId: 'studysharez-6367e',
    authDomain: 'studysharez-6367e.firebaseapp.com',
    storageBucket: 'studysharez-6367e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9KW2Y3t1ubkFMwAWZgVcQ_VpD3QbCY0E',
    appId: '1:748579942028:android:7cde3db68ebe132b4955a9',
    messagingSenderId: '748579942028',
    projectId: 'studysharez-6367e',
    storageBucket: 'studysharez-6367e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvdLB1cdjSPnkHgpJ1ITME7afrdqOmJ-8',
    appId: '1:748579942028:ios:28dfe8d04bbce3d84955a9',
    messagingSenderId: '748579942028',
    projectId: 'studysharez-6367e',
    storageBucket: 'studysharez-6367e.firebasestorage.app',
    iosClientId: '748579942028-dcjga9eosmfbml92d2a6r3d3qa81loch.apps.googleusercontent.com',
    iosBundleId: 'com.example.studysharez',
  );
}
